### ISSUE TITLE
Bootstrap styles conflicting with Django Admin

### ISSUE THREAD

**Issue by bendavis78** [agusmakmun/django-markdown-editor#185]
When using martor in the admin, it causes collapsible fieldsets to be hidden due to the following bootstrap css rule.

```css
.collapse:not(.show) {
    display: none;
}
```

This can be worked around by adding an overriding CSS rule, however, such a workaround should not be necessary.

**Comment by jducastel** [comment]
It also messes with inlines. 

I wondered why my last inline elements weren't saved on an admin form.

It seems like it's because Django admin uses a hidden inline that Martor "un-hide", but it is not functional.

From https://stackoverflow.com/questions/22514186/django-inlines-do-not-save : 

> I used Firebug to inspect the page with the default template stying and it turns out that django hides a final empty form (your proposed temporary solution). So for me the issue was I had set display: inline-block on the inline-related class which all of the inline forms belong to (in django 1.6). To fix it I set display: none on the empty-form class, which only the final inline form belongs to.

**Comment by agusmakmun** [comment]
I thinking to use css namespace to prevent the conflict. Planning to do that.

Related issue: https://github.com/agusmakmun/django-markdown-editor/issues/180

**Comment by Winspear** [comment]
In order to work around this issue, we forked the branch and removed the martor-admin.css file from the MartorWidget class like so:
```    class Media:
        selected_theme = get_theme()
        css = {
            "all": (
                "plugins/css/ace.min.css",
                "plugins/css/resizable.min.css",
                "martor/css/martor.%s.min.css" % selected_theme,
                # removed due to django admin css conflict. See https://github.com/agusmakmun/django-markdown-editor/issues/185
                # "martor/css/martor-admin.min.css",
            )
        }```
We couldn't see what the martor-admin.css was adding to this package. Obviously this is a hack, but in case anybody else is running into this issue.

A full fix would likely require namespacing the file, as mentioned by @agusmakmun

**Comment by gCardinal** [comment]
> In order to work around this issue, we forked the branch and removed the martor-admin.css file from the MartorWidget class like so:
> 
> ```
>         selected_theme = get_theme()
>         css = {
>             "all": (
>                 "plugins/css/ace.min.css",
>                 "plugins/css/resizable.min.css",
>                 "martor/css/martor.%s.min.css" % selected_theme,
>                 # removed due to django admin css conflict. See https://github.com/agusmakmun/django-markdown-editor/issues/185
>                 # "martor/css/martor-admin.min.css",
>             )
>         }
> ```
> 
> We couldn't see what the martor-admin.css was adding to this package. Obviously this is a hack, but in case anybody else is running into this issue.
> 
> A full fix would likely require namespacing the file, as mentioned by @agusmakmun

Doing this, the preview functionality is broken; at least for inlines.

**Comment by glujan** [comment]
Please note that bootstrap theme (`martor/css/martor.bootstrap.min.css`) also conflicts with:
* admin panel sidebar - app name is below models list from that app,
* headers on the whole site, including h1 header in top bar and h2 headers in fieldsets,
* inlines (ie text in the `td.original` is cropped).

I tried using semantic theme but it does not play nicely with other admin plugins I'm using.

Having a CSS theme in a namespace would be great and would probably fix this!

**Comment by voxxelshmoxxel** [comment]
Any updates on this one?

**Comment by agusmakmun** [comment]
Hello everyone, did you guys tried to upgrade the version?

```
pip install martor --upgrade
```

Hopefully this fixed in the latest version.

**Comment by FlorianPix** [comment]
I still have this issue with version=1.6.44.

**Comment by FlorianPix** [comment]
I think the issue does not lie in martor-admin.css or martor.bootstrap.css but instead in the plugins bootstrap.min.css.

My proposed solution is to add `.main-martor ` before every css selector so that it only effects the actual martor compoents and not the rest of the page.

I did that on my [fork](https://github.com/FlorianPix/django-markdown-editor).

**Comment by ryanovas** [comment]
This is still an issue with ^1.7.14, it completely nukes my admin panel styling using django-daisy and the `MARTOR_ENABLE_ADMIN_CSS = False` setting doesn't change anything. Unfortunately this is a dealbreaker for using this package for me :(
